#!/usr/bin/env bash
#
# Generate wrangler.staging.toml for each Worker in the staging deploy set, by transforming
# its wrangler.free.toml. Keeping staging as a pure, deterministic transform of the prod
# free-tier config means staging tracks prod topology automatically (no hand-maintained
# parallel set to drift).
#
# Transform (see docs/runbooks/04-staging-label-gate.md §生成規則):
#   * worker `name`            -> name + "-staging"   (only the top-level name, NOT DO
#                                                       binding names like METER_DO/ChatRoom)
#   * service binding targets  -> target + "-staging" (staging binds the staging upstreams)
#   * service bindings to a Worker NOT in the staging set are DROPPED entirely. Some prod
#     upstreams (e.g. webhook-ingest, which needs PAID Cloudflare Queues) are intentionally
#     absent from the $0 free-tier staging replica; a binding to a Worker that will never be
#     deployed makes the WHOLE api-gateway/app-health-monitor deploy fail (CF code 10143/10144).
#   * D1 database_name         -> dub-core|auth-outbox + "-staging"
#   * D1 database_id / KV id    -> the staging resource ids from staging-resources.env
#   * R2 bucket_name           -> bucket + "-staging"
#   * api-gateway ALLOWED_ORIGINS -> + the staging fe2 origin (CORS)
#   * [triggers] crons         -> DROPPED. The account is already at the free plan's 5/5
#                                 cron cap (prod uses all five), so staging must add ZERO
#                                 crons or CF rejects the deploy. Staging scheduled jobs
#                                 (freeq drain / retention purge / due-soon scan) are thus
#                                 inactive; kick them manually if a review needs them.
#
# Output files are gitignored (build artifacts) — the generator + staging-resources.env are
# the source of truth. Run infra/deploy/setup-staging-resources.sh ONCE first so the ids in
# staging-resources.env are real (not REPLACE_ME placeholders).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"
. infra/deploy/staging-worker-set.sh
set -a; . infra/deploy/staging-resources.env; set +a

# Real PROD resource ids (constants — the values committed in every wrangler.free.toml).
PROD_DUBCORE_ID="d663f9c6-499f-4c67-910d-e08733d5278d"
PROD_AUTHOUTBOX_ID="60a9b8ab-5904-4c1e-8821-e43e0192ce43"
PROD_AUTHKV_ID="71e10ff553a24e0aa0b89929f6ed8643"
PROD_DPKV_ID="b969e6ef6c034ed4ab3b9800f1a0e9ce"
PROD_GANTTKV_ID="fc2d133f9b9f458ab5746f7b40b4bcde"

# Refuse to generate with placeholder ids — they would produce invalid tomls.
for v in STAGING_DUB_CORE_D1_ID STAGING_AUTH_OUTBOX_D1_ID STAGING_AUTH_KV_ID \
         STAGING_DRIVE_PROXY_KV_ID STAGING_GANTT_KV_ID STAGING_WORKERS_SUBDOMAIN; do
  val="${!v:-}"
  case "$val" in
    ""|REPLACE_ME*)
      echo "::error::${v} is a placeholder ('${val}'). Run infra/deploy/setup-staging-resources.sh once to create the staging D1/KV and fill infra/deploy/staging-resources.env." >&2
      exit 1;;
  esac
done

FE2_ORIGIN="https://dub-fe2-app-shell-staging.${STAGING_WORKERS_SUBDOMAIN}.workers.dev"

# The set of staging Worker names that actually get deployed (= each in-set dir's prod name
# + "-staging"). Service bindings whose target is NOT in this set are dropped below.
STAGING_WORKER_NAMES=""
for _d in "${STAGING_WORKER_DIRS[@]}"; do
  _n="$(awk -F'"' '/^name = "/{print $2; exit}' "${_d}/wrangler.free.toml")"
  STAGING_WORKER_NAMES="${STAGING_WORKER_NAMES} ${_n}-staging"
done

# Remove any [[services]] block whose (already -staging-suffixed) target is not a deployed
# staging Worker. Keeps the rest of the toml verbatim.
drop_out_of_set_services() {
  local f="$1"
  awk -v allowed=" ${STAGING_WORKER_NAMES} " '
    function flush() { if (inblk) { if (keep) printf "%s", blk; blk=""; inblk=0; keep=1 } }
    /^\[\[services\]\]/            { flush(); inblk=1; blk=$0 "\n"; keep=1; next }
    inblk && /^\[/                 { flush(); print; next }   # next section ends the block
    inblk {
      blk = blk $0 "\n"
      if ($0 ~ /^service = "/) {
        match($0, /"[^"]*"/); svc=substr($0,RSTART+1,RLENGTH-2)
        if (index(allowed, " " svc " ") == 0) keep=0
      }
      next
    }
    { print }
    END { flush() }
  ' "$f" > "$f.tmp" && mv "$f.tmp" "$f"
}

gen_one() {
  local dir="$1" src="$1/wrangler.free.toml" out="$1/wrangler.staging.toml"
  if [ ! -f "$src" ]; then
    echo "::error::missing $src" >&2; exit 1
  fi
  {
    echo "# AUTO-GENERATED by infra/deploy/gen-staging-configs.sh from wrangler.free.toml."
    echo "# DO NOT EDIT. Edit the .free.toml or the generator instead, then re-run it."
    echo "# [triggers]/crons are intentionally stripped (account is at the 5/5 free cron cap)."
    echo "#"
    awk \
      -v DUBCORE_ID="$PROD_DUBCORE_ID"       -v DUBCORE_STG="$STAGING_DUB_CORE_D1_ID" \
      -v AUTHOUTBOX_ID="$PROD_AUTHOUTBOX_ID" -v AUTHOUTBOX_STG="$STAGING_AUTH_OUTBOX_D1_ID" \
      -v AUTHKV_ID="$PROD_AUTHKV_ID"         -v AUTHKV_STG="$STAGING_AUTH_KV_ID" \
      -v DPKV_ID="$PROD_DPKV_ID"             -v DPKV_STG="$STAGING_DRIVE_PROXY_KV_ID" \
      -v GANTTKV_ID="$PROD_GANTTKV_ID"       -v GANTTKV_STG="$STAGING_GANTT_KV_ID" \
      -v FE2ORIGIN="$FE2_ORIGIN" '
      BEGIN { seen_header=0; in_triggers=0 }
      # --- section headers: drop the whole [triggers] block, pass others through ---
      /^\[/ {
        if ($0 ~ /^\[triggers\]/) { in_triggers=1; next }
        in_triggers=0; seen_header=1; print; next
      }
      in_triggers { next }   # crons lines under [triggers]
      # --- top-level worker name (before any header) -> suffix -staging ---
      (!seen_header && /^name = "/) {
        match($0, /"[^"]*"/); v=substr($0,RSTART+1,RLENGTH-2)
        print "name = \"" v "-staging\""; next
      }
      # --- service binding targets -> suffix -staging (preserve trailing comment) ---
      /^service = "/ {
        match($0, /"[^"]*"/); v=substr($0,RSTART+1,RLENGTH-2); rest=substr($0,RSTART+RLENGTH)
        print "service = \"" v "-staging\"" rest; next
      }
      # --- D1 logical names ---
      /^database_name = "dub-core"/    { print "database_name = \"dub-core-staging\""; next }
      /^database_name = "auth-outbox"/ { print "database_name = \"auth-outbox-staging\""; next }
      # --- R2 bucket names -> suffix -staging (preserve trailing comment) ---
      /^bucket_name = "/ {
        match($0, /"[^"]*"/); v=substr($0,RSTART+1,RLENGTH-2); rest=substr($0,RSTART+RLENGTH)
        print "bucket_name = \"" v "-staging\"" rest; next
      }
      # --- gantt realtime vars: the DO-direct WS base + Origin allow-list must point at
      #     the STAGING gantt worker + staging fe2 origin, not prod (the generic id/CORS
      #     swaps below do not touch a worker hostname inside an arbitrary var value). ---
      /^GANTT_RT_DO_URL_BASE = "/ {
        sub(/dub-gantt-service\./, "dub-gantt-service-staging."); print; next
      }
      /^GANTT_RT_ALLOWED_ORIGINS = "/ {
        print "GANTT_RT_ALLOWED_ORIGINS = \"" FE2ORIGIN "\""; next
      }
      # --- chat realtime vars: same as gantt above. The DO-direct WS base + Origin
      #     allow-list must point at the STAGING chat worker + staging fe2 origin, else
      #     staging fe2 opens the WS against the PROD chat worker and its staging-signed
      #     ticket is rejected (401) — chat realtime silently dead on staging. ---
      /^CHAT_RT_DO_URL_BASE = "/ {
        sub(/dub-chat-service\./, "dub-chat-service-staging."); print; next
      }
      /^CHAT_RT_ALLOWED_ORIGINS = "/ {
        print "CHAT_RT_ALLOWED_ORIGINS = \"" FE2ORIGIN "\""; next
      }
      # --- default: swap resource ids + extend gateway CORS, then print ---
      {
        gsub(DUBCORE_ID, DUBCORE_STG)
        gsub(AUTHOUTBOX_ID, AUTHOUTBOX_STG)
        gsub(AUTHKV_ID, AUTHKV_STG)
        gsub(DPKV_ID, DPKV_STG)
        gsub(GANTTKV_ID, GANTTKV_STG)
        if ($0 ~ /^ALLOWED_ORIGINS = "/) { sub(/"$/, "," FE2ORIGIN "\"") }
        print
      }
    ' "$src"
  } > "$out"
  drop_out_of_set_services "$out"
  echo "  generated $out"
}

echo "generating staging configs (subdomain=${STAGING_WORKERS_SUBDOMAIN}) ..."
for dir in "${STAGING_WORKER_DIRS[@]}"; do
  gen_one "$dir"
done
echo "done: ${#STAGING_WORKER_DIRS[@]} staging configs."
