// @dub/ui/icons — Lucide re-export + IconName -> component registry (凍結案 1-1-7).
// The registry is the single resolution point for the closed `IconName` union;
// consumers pass names, never raw Lucide components.
import {
  Home,
  Calendar,
  CheckSquare,
  Bell,
  MessageCircle,
  Users,
  Settings,
  Search,
  Plus,
  Pencil,
  Trash2,
  ChevronDown,
  ChevronRight,
  ExternalLink,
  AlertTriangle,
  Info,
  X,
  Menu,
  LogOut,
  Shield,
  // P1 additions (fe2〜fe7 icon needs beyond the original 20)
  ListChecks,
  List,
  MessageSquare,
  Maximize,
  Inbox,
  Crosshair,
  Megaphone,
  User,
  History,
  File,
  GripVertical,
  RefreshCw,
  Flag,
  Clock,
  Check,
  CheckCheck,
  BellOff,
  Archive,
  Folder,
  FolderOpen,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "./types";

export type { LucideIcon };

export const iconRegistry: Record<IconName, LucideIcon> = {
  home: Home,
  calendar: Calendar,
  "check-square": CheckSquare,
  bell: Bell,
  "message-circle": MessageCircle,
  users: Users,
  settings: Settings,
  search: Search,
  plus: Plus,
  edit: Pencil,
  trash: Trash2,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "external-link": ExternalLink,
  "alert-triangle": AlertTriangle,
  info: Info,
  x: X,
  menu: Menu,
  "log-out": LogOut,
  shield: Shield,
  // P1 additions — aliases share the same Lucide glyph where semantics match.
  task: ListChecks,
  list: List,
  alert: AlertTriangle, // alias of "alert-triangle" semantics
  chat: MessageSquare,
  warning: AlertTriangle,
  viewport: Maximize,
  inbox: Inbox,
  "message-square": MessageSquare,
  scope: Crosshair,
  megaphone: Megaphone,
  user: User,
  history: History,
  file: File,
  drag: GripVertical,
  refresh: RefreshCw,
  flag: Flag,
  clock: Clock,
  check: Check,
  "check-all": CheckCheck,
  "bell-off": BellOff,
  archive: Archive,
  folder: Folder,
  "folder-open": FolderOpen,
};

// Direct re-export of Lucide for advanced callers (still tree-shakable).
export * from "lucide-react";
