// GENERATED by tool/gen_theme.dart from packages/tokens/tokens.json.
// Do NOT edit by hand. Run: dart run tool/gen_theme.dart
// ignore_for_file: type=lint
import 'dart:ui';

/// A resolved DevHub colour table for one brightness mode.
class DubColors {
  const DubColors({
    required this.brand,
    required this.brandStrong,
    required this.brandSoft,
    required this.surfaceBase,
    required this.surfaceRaised,
    required this.surfaceOverlay,
    required this.surfaceSunken,
    required this.textPrimary,
    required this.textSecondary,
    required this.textMuted,
    required this.textInverse,
    required this.textLink,
    required this.borderDefault,
    required this.borderStrong,
    required this.borderFocus,
    required this.success,
    required this.warning,
    required this.danger,
    required this.info,
  });
  final Color brand;
  final Color brandStrong;
  final Color brandSoft;
  final Color surfaceBase;
  final Color surfaceRaised;
  final Color surfaceOverlay;
  final Color surfaceSunken;
  final Color textPrimary;
  final Color textSecondary;
  final Color textMuted;
  final Color textInverse;
  final Color textLink;
  final Color borderDefault;
  final Color borderStrong;
  final Color borderFocus;
  final Color success;
  final Color warning;
  final Color danger;
  final Color info;
}

/// Light palette, lifted from tokens.json `light`.
const dubLight = DubColors(
  brand: Color(0xFF3358E8),
  brandStrong: Color(0xFF2543C4),
  brandSoft: Color(0xFF5B82FB),
  surfaceBase: Color(0xFFFFFFFF),
  surfaceRaised: Color(0xFFFFFFFF),
  surfaceOverlay: Color(0xFFFFFFFF),
  surfaceSunken: Color(0xFFF8F9FB),
  textPrimary: Color(0xFF1A1E28),
  textSecondary: Color(0xFF3F4759),
  textMuted: Color(0xFF6F7A90),
  textInverse: Color(0xFFFFFFFF),
  textLink: Color(0xFF2543C4),
  borderDefault: Color(0xFFDDE1E9),
  borderStrong: Color(0xFFC3CAD6),
  borderFocus: Color(0xFF3358E8),
  success: Color(0xFF12B76A),
  warning: Color(0xFFF79009),
  danger: Color(0xFFF04438),
  info: Color(0xFF2E90FA),
);

/// Dark palette, lifted from tokens.json `dark`.
const dubDark = DubColors(
  brand: Color(0xFF3358E8),
  brandStrong: Color(0xFF2543C4),
  brandSoft: Color(0xFF5B82FB),
  surfaceBase: Color(0xFF1A1E28),
  surfaceRaised: Color(0xFF2B3140),
  surfaceOverlay: Color(0xFF2B3140),
  surfaceSunken: Color(0xFF12151D),
  textPrimary: Color(0xFFF8F9FB),
  textSecondary: Color(0xFFDDE1E9),
  textMuted: Color(0xFF9AA4B6),
  textInverse: Color(0xFF1A1E28),
  textLink: Color(0xFF8FAEFF),
  borderDefault: Color(0xFF3F4759),
  borderStrong: Color(0xFF535D72),
  borderFocus: Color(0xFF5B82FB),
  success: Color(0xFF12B76A),
  warning: Color(0xFFF79009),
  danger: Color(0xFFF04438),
  info: Color(0xFF2E90FA),
);
