// Design-token → Flutter theme generator (roadmap §7 — design-token sharing).
//
// Reads the DevHub DTCG source of truth `packages/tokens/tokens.json` and emits
// `lib/src/theme/tokens.g.dart` — `const` light/dark colour tables the Flutter
// desktop theme is built from, so the desktop look tracks the web SPA by
// construction (no hand-picked seed to drift).
//
// This is a build-time tool ($0, no deps): the output is committed, and CI can
// re-run it and fail on a diff (same "regenerate → diff = red" guarantee the
// Dart API client uses).
//
//   dart run tool/gen_theme.dart            # regenerate tokens.g.dart
//   dart run tool/gen_theme.dart --check    # fail if the committed file is stale
import 'dart:convert';
import 'dart:io';

// Semantic tokens we lift into the theme (leaf path under a mode -> Dart field).
// Only the semantic layer is mapped (surface/text/border/brand + status hues);
// the raw ramps stay in the JSON.
const _semantic = <String, String>{
  'color/brand/500': 'brand',
  'color/brand/600': 'brandStrong',
  'color/brand/400': 'brandSoft',
  'color/surface/base': 'surfaceBase',
  'color/surface/raised': 'surfaceRaised',
  'color/surface/overlay': 'surfaceOverlay',
  'color/surface/sunken': 'surfaceSunken',
  'color/text/primary': 'textPrimary',
  'color/text/secondary': 'textSecondary',
  'color/text/muted': 'textMuted',
  'color/text/inverse': 'textInverse',
  'color/text/link': 'textLink',
  'color/border/default': 'borderDefault',
  'color/border/strong': 'borderStrong',
  'color/border/focus': 'borderFocus',
  'color/success/500': 'success',
  'color/warning/500': 'warning',
  'color/danger/500': 'danger',
  'color/info/500': 'info',
};

void main(List<String> args) {
  final check = args.contains('--check');
  final root = Directory.current.path; // apps/dt1-desktop
  final tokensPath = '$root/../../packages/tokens/tokens.json';
  final outPath = '$root/lib/src/theme/tokens.g.dart';

  final tokensFile = File(tokensPath);
  if (!tokensFile.existsSync()) {
    stderr.writeln('error: tokens SoT not found at $tokensPath');
    exit(1);
  }
  final json = jsonDecode(tokensFile.readAsStringSync()) as Map<String, dynamic>;

  final light = _extract(json['light'] as Map<String, dynamic>);
  final dark = _extract(json['dark'] as Map<String, dynamic>);

  final buf = StringBuffer()
    ..writeln('// GENERATED by tool/gen_theme.dart from packages/tokens/tokens.json.')
    ..writeln('// Do NOT edit by hand. Run: dart run tool/gen_theme.dart')
    ..writeln('// ignore_for_file: type=lint')
    ..writeln("import 'dart:ui';")
    ..writeln()
    ..writeln('/// A resolved DevHub colour table for one brightness mode.')
    ..writeln('class DubColors {')
    ..writeln('  const DubColors({');
  for (final field in _semantic.values) {
    buf.writeln('    required this.$field,');
  }
  buf.writeln('  });');
  for (final field in _semantic.values) {
    buf.writeln('  final Color $field;');
  }
  buf
    ..writeln('}')
    ..writeln()
    ..writeln('/// Light palette, lifted from tokens.json `light`.')
    ..writeln('const dubLight = DubColors(');
  light.forEach((f, hex) => buf.writeln('  $f: Color(0x$hex),'));
  buf
    ..writeln(');')
    ..writeln()
    ..writeln('/// Dark palette, lifted from tokens.json `dark`.')
    ..writeln('const dubDark = DubColors(');
  dark.forEach((f, hex) => buf.writeln('  $f: Color(0x$hex),'));
  buf.writeln(');');

  final generated = buf.toString();
  final outFile = File(outPath);

  if (check) {
    final current = outFile.existsSync() ? outFile.readAsStringSync() : '';
    if (current.trim() != generated.trim()) {
      stderr.writeln('error: tokens.g.dart is stale. Run: dart run tool/gen_theme.dart');
      exit(1);
    }
    stdout.writeln('tokens.g.dart is up to date');
    return;
  }

  outFile.writeAsStringSync(generated);
  stdout.writeln('wrote ${_semantic.length} colours x2 modes -> $outPath');
}

/// Walk a mode subtree and pull the semantic leaves into `field -> AARRGGBB`.
Map<String, String> _extract(Map<String, dynamic> mode) {
  final out = <String, String>{};
  _semantic.forEach((path, field) {
    final parts = path.split('/');
    dynamic node = mode;
    for (final p in parts) {
      node = (node as Map<String, dynamic>?)?[p];
    }
    final value = (node as Map<String, dynamic>?)?[r'$value'] as String?;
    if (value == null) {
      stderr.writeln('error: missing token "$path" in tokens.json');
      exit(1);
    }
    out[field] = _toArgb(value);
  });
  return out;
}

/// "#rrggbb" (or "#rgb") -> "FFrrggbb" (opaque ARGB hex for `Color(0x...)`).
String _toArgb(String hex) {
  var h = hex.replaceFirst('#', '').toUpperCase();
  if (h.length == 3) {
    h = h.split('').map((c) => '$c$c').join();
  }
  if (h.length == 6) return 'FF$h';
  if (h.length == 8) return h; // already has alpha
  throw FormatException('unexpected colour "$hex"');
}
